#+TITLE:     Manual for multi-site BC with BASFOR
#+AUTHOR:    Marcel van Oijen
#+OPTIONS:   ^:nil, _:nil
#+LASTEDIT:  2016.03.01 15:35:14

* Introduction
This manual shows step-by-step how to carry out a multi-site Bayesian
calibration using forest model BASFOR. The procedure was tested on
the files in directory 'BASFOR_2015-04-21'. Calibration data
consist of eddy-covariance data and ancillary data from European
forest sites, both coniferous and deciduous.

* Calibration data
- During calibration, the calibration data are compared to values of
  model output variables. The list of the model's output variables
  thus determines which data can be used. To see which output
  variables are defined for BASFOR it is easiest to simply initialise
  the model (e.g. by running the general initialisation file
  'initialise_BASFOR_general.R') and type 'outputNames' in the
  console. And type 'outputUnits' to see the array with the units.
  - Alternatively, the list of output variables can be found in the
    FORTRAN-file 'model/BASFOR.f90', where the variables are
    calculated. [NOTE: the two files 'initialise_BASFOR_general.R' and
    'BASFOR.f90' must stay consistent with each other, so if you
    decide to add or delete output variables, make the appropriate
    changes in both files].
- The calibration can handle four types of data files: see the
  examples that are given for how they should be formatted:
  - Ancillary data (e.g. 'data_ancillary_DECIDUOUS_DE-Hai.txt'):
    txt-files with five columns: (1) variable name, (2) measurement
    year (3) measurement day, (4) measurement value, (5) measurement
    uncertainty
  - Annual data (e.g. 'data_ANNUAL_DECIDUOUS_DE-Hai.txt'): txt-files
    with five columns. The columns are similar to those for the
    ancillary data, but the second and third column now represent the
    last day of the year over which the variable was averaged and the
    fourth column gives the annual mean rather than a measurement for
    that specific day.
    - Annual data can be provided for any output variable from the
      model, i.e. ancillary variables as well as EC-variables.
  - Daily data (e.g. 'data_daily_DECIDUOUS_DE-Hai.txt'), with the same
    five-column structure as the ancillary data.
  - EC-data (e.g. 'data_EC_DECIDUOUS_DE-Hai.txt'): txt-files with six
    columns with headers representing year and day of measurement,
    Reco, NEE, GPP, ET.
  - There are differences between these data-file types in how they
    are handled in the calibration.
    - The 'daily' and 'EC' data can be time-averaged over multiple
      days (e.g. 30 to get monthly averages) which is specified in the
      file 'BC_BASFOR_MCMC_init_general.R'. The same time-averaging
      will then automatically be applied to the corresponding model
      output variables.
    - The annual data are interpreted as already representing annual
      averages (so the calibration code ensures that the corresponding
      model variables are annual-averaged too).
    - The ancillary data cannot be time-averaged.

* Multi-site BC step-by-step
** Calibration data
- Put calibration data files in subdirectory 'data'.
** Initialisation files
- For each site, put a model initialisation file in subdirectory
  'initialisation'.
- Check that each initialisation file refers to the correct model
  dll-file ('MODEL_dll <- BASFOR_conif.DLL' or 'MODEL_dll <-
  BASFOR_decid.DLL').
** Weather data
- For each site, add a weather file to subdirectory 'weather'.
** Parameters: default settings
- Create a txt-file with, for every site, default values of all
  parameters in the model.
  - Copy, rename and adapt 'parameters_6sites.txt' (or use it!)
** Parameters: calibration settings
- Create a txt-file that specifies the parameters to be calibrated,
  and their prior distribution.
  - For example: copy, rename and adapt 'parameters_BC_DECIDUOUS.txt'
  - The file must have five columns: (1) parameter name, (2) parameter
    minimum, (3) parameter mode, (4) parameter maximum, (5) sites to
    which the row corresponds.
  - In column 5, specify '1' if you are doing a single-site
    calibration, '1:nSites' if you are doing a multi-site calibration
    and the parameter is generic, and so-on.)
** MCMC-initialisation file
- Copy, rename and adapt 'BC_BASFOR_MCMC_init_DECIDUOUS.R' or another of
  the provided Bayesian Calibration initialisation files.
- Set the chain length (nChain). Set it to a small number like 20
  while testing your code and then for proper calibration set it to
  10^4 - 10^5:
  - *nChain <- as.integer(...)*
- Give the name of the file with your prior for the calibration parameters:
  - *file_prior <- ...*
- List the names of the model initialisation files:
  - *sitesettings_files <- c(...)*
- List the names of files with ancillary data. If a site has no
  ancillary data just assign ''. IMPORTANT: Use the same order as
  for the initialisation files:
  - *sitedata_ancillary_files <- c(...)*
- List the names of files with annual data. If a site has no
  annual data just assign ''. IMPORTANT: Use the same order as
  for the initialisation files:
  - *sitedata_annual_files <- c(...)*
- List the names of files with daily data. If a site has no
  ancillary data just assign ''. IMPORTANT: Use the same order as
  for the initialisation files:
  - *sitedata_daily_files <- c(...)*
- List the names of files with eddy-covariance (EC) data. If a site has no
  EC-data just assign ''. IMPORTANT: Use the same order as
  for the initialisation files:
  - *sitedata_EC_files <- c(...)*
** Script file for the Bayesian calibration
- Copy, rename and adapt 'BC_BASFOR_DECIDUOUS.R' or another of the
  example files.
  - The first 'sourced' R-file should be the MCMC-initialisation file
    that we have specified before.
** Run the calibration
- Run the script file for the Bayesian calibration
** Inspect results
- Standard the following files are produced:
  - 'BASFOR_parModes_TIME].txt'
    - Table of ALL parameters (not just the calibrated ones) with
      multiple columns per site: mode of prior, mode of posterior
      (MAP), maximum likelihood estimate (MaxL)
  - 'BC_parameters_priorbeta_histograms[_TIME].pdf'
    - For each calibrated parameter a histogram of posterior with
      superimposed a curve for the prior. First the generic parameters
      followed by the site-specific parameters, in order of site
      number.
  - 'BC_parameters_traceplots[_TIME].pdf'
    - For each calibrated parameter a trace plot. Generic parameters
      are shown first, followed by the site-specific parameters, in
      order of site number.
  - 'BC_BASFOR_SITE[SITENUMBER][_TIME].pdf'
    - One such file per site, with for each calibration variable a
      time plot showing the data and three simulation curves: prior
      mode, MAP, MaxL. Also included, in dashed lines, are uncertainty
      intervals [Q5,Q95].

* Notes on data used in the example files
- Please ask for permission to use calibration data provided here
